### ISSUE TITLE
UBIKSolver.uplugin needs targeted platforms in order to be included in the build

### ISSUE THREAD

**Issue by magerbeton** [JonasMolgaard/UBIKSolver#11]
This is an issue I encountered while trying to get a build working on quest 2 (android). It did not include the animation blueprint which contained the UBIK node.
By adding
```.cs
"SupportedTargetPlatforms": [
		"Win64",
		"Android"
	]
```
to the UBIKSolver.uplugin I got it included in the build for Windows (HTC-Vive) and Android (Oculus Quest 2) on UE 5.1.1.

**Comment by JonasMolgaard** [comment]
thanks for the pullrequest, it's been approved. Closing this issue.
