### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by LucaFilitz** [JonasMolgaard/UBIKSolver#13]
Could you please add a license (hopefully MIT) to the repo? :)

**Comment by RWOverdijk** [comment]
I just used this repo, [the unity one](https://github.com/dabeschte/VRArmIK) and [the thesis](https://diglib.tugraz.at/download.php?id=5c4a48dc5a282&location=browse) for inspiration and wrote my own. It's fun to learn from and it makes sure you don't get issues with licenses.

For @JonasMolgaard I don't know if it's on purpose, but a repository without a license means people can't do much with it (default copyright laws apply).

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.
>
> **Source: [github docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)**

**Comment by JonasMolgaard** [comment]
Huh thanks for letting me know, that was definetely not my intention. I wanted this work to be publicly available for anyone to use without any constraints.

How do I add such a license?

Jonas

Den 29. maj 2023 kl. 10.43 skrev Roberto Wesley Overdijk ***@***.***>:

﻿

I just used this repo, the unity one<https://github.com/dabeschte/VRArmIK> and the thesis<https://diglib.tugraz.at/download.php?id=5c4a48dc5a282&location=browse> for inspiration and wrote my own. It's fun to learn from and it makes sure you don't get issues with licenses.

For @JonasMolgaard<https://github.com/JonasMolgaard> I don't know if it's on purpose, but a repository without a license means people can't do much with it (default copyright laws apply).

You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

Source: github docs<https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository>

**Comment by RWOverdijk** [comment]
I’ve made a pull request on GitHub here https://github.com/JonasMolgaard/UBIKSolver/pull/14

I’ve included a link to help you pick a different license if you don’t like the one I picked. Otherwise you just have to accept and it’s added 😄

**Comment by jimsimonz** [comment]
@JonasMolgaard be great if you could accept the attached pull request/add an MIT license. At the moment this is unusable in a commercial project without the license in place. Just needs the MIT license file in the root folder ( or another if you prefer).

**Comment by RWOverdijk** [comment]
🎉

**Comment by JonasMolgaard** [comment]
Sry for the wait.. have had a ton to look into

Jonas

Den 20. sep. 2023 kl. 10.32 skrev Roberto Wesley Overdijk ***@***.***>:

﻿

🎉
