### ISSUE TITLE
Grabbing is broken since UBIK hands are offset from VR Template hands

### ISSUE THREAD

**Issue by markentingh** [JonasMolgaard/UBIKSolver#15]
I tried setting this up using a default VR Template in UE 5.3, and everything works. The only issue that I'm having is that the UBIK mannequin hands are offset from the VR Template hands. None of the hand positions align with the VR Template hands, such as Left Grip, Left Aim, or just Left. Trying to make adjustments to the UBIK settings defaults for Local Hand Offset & Local Hand Rotation Offset is a nightmare. I just want to be able to get these hands to align with the VR Template provided hands so that grabbing works correctly.

**Comment by JonesyPMD** [comment]
hey did you find a solution for this?

**Comment by markentingh** [comment]
I did. Let me remember hahaha.... I think what I did was use the Motion Controller Left & Right Aim components to set the Left Hand & Right Hand Transforms for UBIK, then I  set up hand sockets on the character skeleton for various items that I wanted to pick up. Then, I set up the GrabComponent blueprint to use the Attach Component To Component node for left & right hands and specified the hand socket name based on the Grab Type. 

So for example, I added a Grab Type of "Flashlight" to the GrabType enum blueprint, added a new hand socket to each hand in my character skeleton called flashlight_l & flashlight_r, created a new Animation Sequence for the flashlight right hand, and attached the flashlight to the right hand flashlight_r socket (as a preview asset) within the animation sequence, then aligned the flashlight to the hand and curled the fingers the way I wanted them to grip the flashlight. I set up this animation sequence to trigger within the UBIK animation blueprint when the user grabs an actor that contains the GrabComponent blueprint of GrabType "flashlight", and the flashlight magically appeared gripped in my hand. I also set up the UBIK animation blueprint to utilize the flashlight right hand animation sequence for the left hand too by setting up a Mirror Data Table for my character skeleton and then using the Mirror node within the UBIK AnimGraph. Let me show you some screenshots...

![Image 530](https://github.com/JonasMolgaard/UBIKSolver/assets/2896371/cb670d59-7522-4d56-9655-5a597ae5b9d6)
![Image 529](https://github.com/JonasMolgaard/UBIKSolver/assets/2896371/7f043e6e-b424-4cd5-834c-c906f4b14ca9)
![Image 528](https://github.com/JonasMolgaard/UBIKSolver/assets/2896371/d881b86a-df5d-4148-a1d5-04b56a2d9f39)
![Image 527](https://github.com/JonasMolgaard/UBIKSolver/assets/2896371/307f45c3-d495-4104-8541-fc73f345db40)
![Image 526](https://github.com/JonasMolgaard/UBIKSolver/assets/2896371/8b2bf995-1990-49c2-8de9-f8063cce16a6)
![Image 531](https://github.com/JonasMolgaard/UBIKSolver/assets/2896371/d9dbcab0-45ad-4dca-b0f6-e9754288f4f7)

**Comment by JonesyPMD** [comment]
Thank you so much i will look into it!

**Comment by JonasMolgaard** [comment]
Thanks for the detailed description markentingh. I assume this issue is solved, and closing it.
