### ISSUE TITLE
UPlugin file error with UE 5.3.0

### ISSUE THREAD

**Issue by Orangers1** [JonasMolgaard/UBIKSolver#16]
The UPlugin file doesn't seem to work with the latest unreal engine version (5.3.0), and won't build properly due to some minor errors. (might just be me though, and I fixed the issue with a slightly modified UPlugin file)

*edit fixed some grammar for readability

Modified file (just in text format you can modify yourself if needed, but this fixed it for me)
---------------------------------------------------------------------------------------------------
{
	"FileVersion": 3,
	"Version": 1,
	"VersionName": "1.1",
	"FriendlyName": "UBIKSolver",
	"Description": "UpperBody IK Solver",
	"Category": "Animation",
	"CreatedBy": "Sticky Snout Studio (Jonas Molgaard)",
	"CreatedByURL": "https://stickysnoutstudio.com/",
	"DocsURL": "",
	"MarketplaceURL": "",
	"SupportURL": "",
	"CanContainContent": false,
	"IsBetaVersion": false,
	"Installed": false,
	"SupportedTargetPlatforms": [
		"Win64",
		"Android"
	],
	"Modules": [
		{
			"Name": "UBIKRuntime",
			"Type": "Runtime",
			"LoadingPhase": "Default"
		},
		{
			"Name": "UBIKEditor",
			"Type": "UncookedOnly",
			"LoadingPhase": "Default"
		}
	]
}

**Comment by kjduling** [comment]
Created a [pull request](https://github.com/JonasMolgaard/UBIKSolver/pull/17)

**Comment by JonasMolgaard** [comment]
Approved pullrequest and closing this issue. Thanks guys.
