### ISSUE TITLE
Cant compile the plugin

### ISSUE THREAD

**Issue by CardsAndGamesYT** [JonasMolgaard/UBIKSolver#19]
every time i try to compile the plugin from source for ue 5.0.3 it says that "`GetSkinnedAsset`: is not a member of `USkeletalMeshComponent`"

i see this being referenced in https://github.com/JonasMolgaard/UBIKSolver/issues/8 and https://github.com/JonasMolgaard/UBIKSolver/pull/18 but it doesn't seem to be fixed for me. i jsut downloaded the plugin from the master branch today.

**Comment by kjduling** [comment]
My advice is to take a look at https://github.com/JonasMolgaard/UBIKSolver/pull/18/files and reverse the changes in your local copy.  If that works like I expect it will, wrap the changes in an ifdef and submit a PR.  I didn't think to make it backwards compatible.
