### ISSUE TITLE
Hands moving with Camera, how to disable?

### ISSUE THREAD

**Issue by Stilton0502** [JonasMolgaard/UBIKSolver#6]
How do I disable the moving of the hands with the camera, it causing offsets between my controllers and in game hands.
Thanks!

**Comment by kjduling** [comment]
It sounds like you've attached your controllers as children to your HMD.  They should be peers.  Jonas did the same thing in one of his videos and corrects it: https://youtu.be/cxVIBGg59-I?list=PLT4SeajOa6mZuzBdp5GC5NrKy4pdnVj0b&t=811

**Comment by JonasMolgaard** [comment]
Closing this issue as kjduling mentions the fix i used in the video.
