### ISSUE TITLE
UE5 module not loading on Preview 1

### ISSUE THREAD

**Issue by Obumbrata** [JonasMolgaard/UBIKSolver#7]
Hi, I know this plugin is made for UE4 but its been working great on UE5 until Preview 1. This is the error I get.

Procedure entry point ?OneVector@FVector@@2U1@B could not be located in the dynamic link library.

**Comment by kjduling** [comment]
I have it working in UE 5.3.1

**Comment by Obumbrata** [comment]
Awesome! Haven't tried it since, will give it a go soon. Thanks!
